# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
    # Artifact name
        name: Jar_Snapshot_Build # optional
    # A file, directory or wildcard pattern that describes what to upload
        path: target/bukkitcord-*.jar
    - name: Upload to repo
      run: echo "Deploying to the Github..."
    - run: git clone --depth=1 https://${{ secrets.REPO_KEY }}@github.com/DreamlessRealm/maven-repo.git /home/runner/maven-repo
    - run: mvn deploy -DaltDeploymentRepository=maven-repo::default::file:/home/runner/maven-repo
    - run: git config --global user.email "kinomc@qq.com"
    - run: git config --global user.name "Github Actions Bot"
    - run: cd /home/runner/maven-repo
    - run: git add .
    - run: git commit -m "Auto update by Github Actions"
    - run: git push --force
